# Generated by Django 6.0.1 on 2026-06-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_semanticmemory_subject_mutability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodicmemory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='importanalysis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='semanticmemory',
            name='category',
            field=models.CharField(choices=[('identity', '身份'), ('preference', '偏好'), ('experience', '经历'), ('relationship', '互动规律')], default='preference', max_length=50),
        ),
        migrations.AlterField(
            model_name='semanticmemory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='semanticmemory',
            name='source',
            field=models.CharField(choices=[('ai', 'AI 自动整理'), ('user', '用户手动维护'), ('import', '导入聊天记录预处理')], default='ai', max_length=10),
        ),
        migrations.AlterField(
            model_name='timechunk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topictag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
