# Generated by Django 6.0.1 on 2026-07-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_messageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='importanalysis',
            name='completed_chunks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importanalysis',
            name='failed_chunks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importanalysis',
            name='stage',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='importanalysis',
            name='total_chunks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importanalysis',
            name='status',
            field=models.CharField(choices=[('pending', '待分析'), ('analyzing', '分析中'), ('partial', '部分完成，可断点继续'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=20),
        ),
    ]
