# Generated by Django 6.0.1 on 2026-05-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_chat_message_fts'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_messag_charact_79437c_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_messag_charact_ac3c49_idx',
        ),
        migrations.AddField(
            model_name='character',
            name='chat_sender_name',
            field=models.CharField(blank=True, default='', help_text='聊天记录中此角色对应的发送人名字（如大白鹅）', max_length=50),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
