# Generated by Django 6.0.1 on 2026-05-19 11:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_char_sender_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('timestamp', models.CharField(max_length=50)),
                ('msg_index', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.character')),
            ],
            options={
                'db_table': 'chat_message',
                'indexes': [models.Index(fields=['character', 'sender'], name='chat_messag_charact_79437c_idx'), models.Index(fields=['character', 'msg_index'], name='chat_messag_charact_ac3c49_idx')],
            },
        ),
    ]
