# Generated by Django 6.0.1 on 2026-05-19 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_recreate_chatmsg"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodicMemory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("summary", models.CharField(max_length=200)),
                ("keywords", models.CharField(default="", max_length=200)),
                ("importance", models.FloatField(default=0.5)),
                ("raw_messages", models.TextField()),
                ("msg_count", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("friend", models.ForeignKey(
                    to="web.Friend", on_delete=models.CASCADE
                )),
            ],
            options={"db_table": "episodic_memory"},
        ),
        migrations.CreateModel(
            name="SemanticMemory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("fact", models.CharField(max_length=500)),
                ("category", models.CharField(
                    default="other", max_length=50,
                    choices=[
                        ("preference", "偏好"), ("experience", "经历"),
                        ("personality", "性格"), ("relationship", "关系"),
                        ("other", "其他"),
                    ]
                )),
                ("confidence", models.FloatField(default=0.5)),
                ("evidence", models.TextField(default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("friend", models.ForeignKey(
                    to="web.Friend", on_delete=models.CASCADE
                )),
                ("replaced_by", models.ForeignKey(
                    blank=True, null=True, on_delete=models.SET_NULL,
                    to="web.SemanticMemory"
                )),
            ],
            options={"db_table": "semantic_memory"},
        ),
        migrations.AddField(
            model_name="Friend",
            name="last_reflection_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name="EpisodicMemory",
            index=models.Index(fields=["friend", "-created_at"], name="ep_friend_created"),
        ),
        migrations.AddIndex(
            model_name="SemanticMemory",
            index=models.Index(
                fields=["friend", "is_active", "category"], name="sem_friend_active_cat"
            ),
        ),
        migrations.AddIndex(
            model_name="SemanticMemory",
            index=models.Index(
                fields=["friend", "-confidence"], name="sem_friend_conf"
            ),
        ),
    ]
